sudo: false
language: node_js
#cache:
#  directories:
#    - node_modules
notifications:
  email: false
node_js:
  - 5
  - 4
  # - iojs-v3
  # - iojs-v2
  # - iojs-v1
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
